[package]
name = "yanfa7"
version = "2.0.4"
description = "研发七部工具包"
authors = ["gulei"]
edition = "2021"

[lib]
name = "yanfa7_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
tauri-plugin-store = "2"
tauri-plugin-os = "2"
tauri-plugin-opener = "2"
tauri-plugin-window-state = "2"
tauri-plugin-drag = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"
